# Generated by Django 3.2.12 on 2022-04-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sigle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sigle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmc_app.fonction')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmc_app.grade')),
            ],
        ),
    ]
